# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
commands:
  install-bazel:
    steps:
      - run:
          name: Install bazel
          command: |
            curl -OL https://github.com/bazelbuild/bazel/releases/download/0.28.0/bazel-0.28.0-installer-linux-x86_64.sh
            chmod +x bazel-0.28.0-installer-linux-x86_64.sh
            sudo ./bazel-0.28.0-installer-linux-x86_64.sh
            rm ./bazel-0.28.0-installer-linux-x86_64.sh
            bazel info release
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/h-fam/errdiff
    steps:
      - checkout
      - install-bazel
      # specify any bash command here prefixed with `run: `
      - run: bazel build ...
      - run: bazel test ...
