# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.1/language-go/ for more details
version: 2.1
commands:
  install-bazel:
    steps:
      - run:
          name: Install bazel
          command: |
            curl -OL https://github.com/bazelbuild/bazel/releases/download/0.28.0/bazel-0.28.0-installer-linux-x86_64.sh
            chmod +x bazel-0.28.0-installer-linux-x86_64.sh
            sudo ./bazel-0.28.0-installer-linux-x86_64.sh
            rm ./bazel-0.28.0-installer-linux-x86_64.sh
            bazel info release

jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.12
    working_directory: ~/code/
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: go build .
      - run: go test .
